import Head from "next/head";
import Trade from "@/components/pages/Trade";

export default function TradePage() {
  return (
    <>
      <Head>
        <title>Perennial - Trade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Trade />
    </>
  );
}
